package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Annet generated by hbm2java
 */
public class Annet  implements java.io.Serializable {


     private String brukernavn;
     private String fastlonn;

    public Annet() {
    }

	
    public Annet(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public Annet(String brukernavn, String fastlonn) {
       this.brukernavn = brukernavn;
       this.fastlonn = fastlonn;
    }
   
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public String getFastlonn() {
        return this.fastlonn;
    }
    
    public void setFastlonn(String fastlonn) {
        this.fastlonn = fastlonn;
    }




}


