package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Bosted generated by hbm2java
 */
public class Bosted  implements java.io.Serializable {


     private int postnummer;
     private String poststed;

    public Bosted() {
    }

    public Bosted(int postnummer, String poststed) {
       this.postnummer = postnummer;
       this.poststed = poststed;
    }
   
    public int getPostnummer() {
        return this.postnummer;
    }
    
    public void setPostnummer(int postnummer) {
        this.postnummer = postnummer;
    }
    public String getPoststed() {
        return this.poststed;
    }
    
    public void setPoststed(String poststed) {
        this.poststed = poststed;
    }




}


