package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Kunde generated by hbm2java
 */
public class Kunde  implements java.io.Serializable {


     private String brukernavn;
     private Integer avslag;

    public Kunde() {
    }

	
    public Kunde(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public Kunde(String brukernavn, Integer avslag) {
       this.brukernavn = brukernavn;
       this.avslag = avslag;
    }
   
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public Integer getAvslag() {
        return this.avslag;
    }
    
    public void setAvslag(Integer avslag) {
        this.avslag = avslag;
    }




}


