package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ordre generated by hbm2java
 */
public class Ordre  implements java.io.Serializable {


     private OrdreId id;
     private Date datoendret;
     private Date datolevert;
     private Date bekreftet;
     private String betaltstatus;
     private Integer selskapnr;

    public Ordre() {
    }

	
    public Ordre(OrdreId id) {
        this.id = id;
    }
    public Ordre(OrdreId id, Date datoendret, Date datolevert, Date bekreftet, String betaltstatus, Integer selskapnr) {
       this.id = id;
       this.datoendret = datoendret;
       this.datolevert = datolevert;
       this.bekreftet = bekreftet;
       this.betaltstatus = betaltstatus;
       this.selskapnr = selskapnr;
    }
   
    public OrdreId getId() {
        return this.id;
    }
    
    public void setId(OrdreId id) {
        this.id = id;
    }
    public Date getDatoendret() {
        return this.datoendret;
    }
    
    public void setDatoendret(Date datoendret) {
        this.datoendret = datoendret;
    }
    public Date getDatolevert() {
        return this.datolevert;
    }
    
    public void setDatolevert(Date datolevert) {
        this.datolevert = datolevert;
    }
    public Date getBekreftet() {
        return this.bekreftet;
    }
    
    public void setBekreftet(Date bekreftet) {
        this.bekreftet = bekreftet;
    }
    public String getBetaltstatus() {
        return this.betaltstatus;
    }
    
    public void setBetaltstatus(String betaltstatus) {
        this.betaltstatus = betaltstatus;
    }
    public Integer getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(Integer selskapnr) {
        this.selskapnr = selskapnr;
    }




}


