package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Ordretabell generated by hbm2java
 */
public class Ordretabell  implements java.io.Serializable {


     private OrdretabellId id;
     private String rettnummer;

    public Ordretabell() {
    }

    public Ordretabell(OrdretabellId id, String rettnummer) {
       this.id = id;
       this.rettnummer = rettnummer;
    }
   
    public OrdretabellId getId() {
        return this.id;
    }
    
    public void setId(OrdretabellId id) {
        this.id = id;
    }
    public String getRettnummer() {
        return this.rettnummer;
    }
    
    public void setRettnummer(String rettnummer) {
        this.rettnummer = rettnummer;
    }




}


