package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Retter generated by hbm2java
 */
public class Retter  implements java.io.Serializable {


     private String rettnummer;
     private String navn;
     private String beskrivelse;
     private String ingredienser;
     private Integer kalorier;
     private Integer vekt;
     private Integer pris;

    public Retter() {
    }

	
    public Retter(String rettnummer, String navn) {
        this.rettnummer = rettnummer;
        this.navn = navn;
    }
    public Retter(String rettnummer, String navn, String beskrivelse, String ingredienser, Integer kalorier, Integer vekt, Integer pris) {
       this.rettnummer = rettnummer;
       this.navn = navn;
       this.beskrivelse = beskrivelse;
       this.ingredienser = ingredienser;
       this.kalorier = kalorier;
       this.vekt = vekt;
       this.pris = pris;
    }
   
    public String getRettnummer() {
        return this.rettnummer;
    }
    
    public void setRettnummer(String rettnummer) {
        this.rettnummer = rettnummer;
    }
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public String getBeskrivelse() {
        return this.beskrivelse;
    }
    
    public void setBeskrivelse(String beskrivelse) {
        this.beskrivelse = beskrivelse;
    }
    public String getIngredienser() {
        return this.ingredienser;
    }
    
    public void setIngredienser(String ingredienser) {
        this.ingredienser = ingredienser;
    }
    public Integer getKalorier() {
        return this.kalorier;
    }
    
    public void setKalorier(Integer kalorier) {
        this.kalorier = kalorier;
    }
    public Integer getVekt() {
        return this.vekt;
    }
    
    public void setVekt(Integer vekt) {
        this.vekt = vekt;
    }
    public Integer getPris() {
        return this.pris;
    }
    
    public void setPris(Integer pris) {
        this.pris = pris;
    }




}


