package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Rolle generated by hbm2java
 */
public class Rolle  implements java.io.Serializable {


     private RolleId id;

    public Rolle() {
    }

    public Rolle(RolleId id) {
       this.id = id;
    }
   
    public RolleId getId() {
        return this.id;
    }
    
    public void setId(RolleId id) {
        this.id = id;
    }




}


