package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Selskapkunde generated by hbm2java
 */
public class Selskapkunde  implements java.io.Serializable {


     private SelskapkundeId id;

    public Selskapkunde() {
    }

    public Selskapkunde(SelskapkundeId id) {
       this.id = id;
    }
   
    public SelskapkundeId getId() {
        return this.id;
    }
    
    public void setId(SelskapkundeId id) {
        this.id = id;
    }




}


