package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Selskaper generated by hbm2java
 */
public class Selskaper  implements java.io.Serializable {


     private int selskapnr;
     private Integer avslag;
     private Integer akkumulertsalg;

    public Selskaper() {
    }

	
    public Selskaper(int selskapnr) {
        this.selskapnr = selskapnr;
    }
    public Selskaper(int selskapnr, Integer avslag, Integer akkumulertsalg) {
       this.selskapnr = selskapnr;
       this.avslag = avslag;
       this.akkumulertsalg = akkumulertsalg;
    }
   
    public int getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(int selskapnr) {
        this.selskapnr = selskapnr;
    }
    public Integer getAvslag() {
        return this.avslag;
    }
    
    public void setAvslag(Integer avslag) {
        this.avslag = avslag;
    }
    public Integer getAkkumulertsalg() {
        return this.akkumulertsalg;
    }
    
    public void setAkkumulertsalg(Integer akkumulertsalg) {
        this.akkumulertsalg = akkumulertsalg;
    }




}


