package domain;
// Generated 13.mar.2013 17:31:33 by Hibernate Tools 3.2.1.GA



/**
 * Utkjoringsbil generated by hbm2java
 */
public class Utkjoringsbil  implements java.io.Serializable {


     private int bilnr;
     private String regnummer;
     private String status;

    public Utkjoringsbil() {
    }

    public Utkjoringsbil(int bilnr, String regnummer, String status) {
       this.bilnr = bilnr;
       this.regnummer = regnummer;
       this.status = status;
    }
   
    public int getBilnr() {
        return this.bilnr;
    }
    
    public void setBilnr(int bilnr) {
        this.bilnr = bilnr;
    }
    public String getRegnummer() {
        return this.regnummer;
    }
    
    public void setRegnummer(String regnummer) {
        this.regnummer = regnummer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


